apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "schema-registry-service.fullname" . }}
  labels:
    {{- include "schema-registry-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "schema-registry-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "schema-registry-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "schema-registry-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
          - name: DB_HOST
            valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db_host
          - name: DB_USERNAME
            valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db_username
          - name: DB_SECRET
            valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db_password
          - name: DB_PORT
            valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db_port
          - name: DB_NAME
            valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: db_name
          - name: DB_EXECUTE_MIGRATIONS
            value: {{ .Values.dbExecuteMigrations }}
          - name: REDIS_HOST
            value: {{ .Values.redisHost }}
          - name: REDIS_PORT
            value: {{ .Values.redisPort }}
          - name: ASSETS_URL
            value: {{ .Values.assetsUrl }}
          - name: ASYNC_SCHEMA_UPDATES
            value: {{ .Values.asyncSchemaUpdates }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
