{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Release.Namespace }}
  name: schema-registry-api-ingress-default
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: '50m'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  {{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4}}
  {{- end }}

spec:
  rules:
    - host: '{{ .Values.ingress.host }}'
      http:
        paths:
          - path: /schema-registry-api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: schema-registry-service
                port:
                  number: {{ .Values.service.port }}
{{- end }}
