apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: db-secrets
type: Opaque
data:
  db_host: {{ .Values.db_host | b64enc}}
  db_username: {{ .Values.dbUsername | b64enc}}
  db_password: {{ .Values.dbSecret | b64enc}}
  db_port: {{ .Values.dbPort | b64enc}}
  db_name: {{ .Values.dbName | b64enc}}
