name: "Publish docker image to staging registry"

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

env:
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}
  LOCATION: us-east4
  PROJECT_ID: federato
  REPOSITORY: schema-registry-service
  IMAGE: schema-registry-service-staging

jobs:
  setup-build-push:
    name: Setup, Build, and Publish Image
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Bumped version to')"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Download Private GitHub Actions
        uses: ./.github/actions/download-private-actions
        with:
          appId: ${{ secrets.ACTIONS_APP_ID }}
          appKey: ${{ secrets.ACTIONS_APP_KEY }}
      - name: Build and Push Docker Image
        uses: ./.github/actions/downloaded/build-and-push-docker-image
        with:
          garJsonKey: ${{ secrets.GAR_JSON_KEY }}
          image: ${{ env.IMAGE }}
          repository: ${{ env.REPOSITORY }}
          useStagingTagging: "true"
  deploy-to-staging:
    name: Deploy schema-registry-service to Staging
    needs: [setup-build-push]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set TAG Environment Variable
        run: |
          export TAG=$(echo ${{ github.sha }} | cut -c1-6)
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Download Private GitHub Actions
        uses: ./.github/actions/download-private-actions
        with:
          appId: ${{ secrets.ACTIONS_APP_ID }}
          appKey: ${{ secrets.ACTIONS_APP_KEY }}
      - name: Update Staging Helm Image
        uses: ./.github/actions/downloaded/update-helm-image
        with:
          deploymentsAppId: ${{ secrets.APP_DEPLOYMENTS_APP_ID }}
          deploymentsAppKey: ${{ secrets.APP_DEPLOYMENTS_APP_KEY }}
          newImageTag: ${{ env.TAG }}
          service: ${{ env.REPOSITORY }}
