name: "Validate Helm Chart and Kubernetes Manifests"

on:
  pull_request:
    branches:
      - trunk

jobs:
  validate-k8s:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run helm template and kubeval
        uses: stefanprodan/kube-tools@v1
        with:
          command: |
            echo "Run kubeval"
            helmv3 template ./chart | kubeval --strict --ignore-missing-schemas
